// <auto-generated />
using ByGrace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByGrace.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240402160655_IniciandoBancoDeDados")]
    partial class IniciandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ByGrace.Classes.Produtos", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProduto"));

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnOrder(1);

                    b.Property<int>("TamanhoProduto")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<double>("ValorProduto")
                        .HasColumnType("float")
                        .HasColumnOrder(3);

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
